### ISSUE TITLE
Remove redundant files from the repository

### ISSUE THREAD

**Issue by jac08h** [Wenzhi-Ding/py_reminder#4]
Are the **dist** and **build** directories necessary? I think they add unnecessary clutter to the repo. 
It'd be nice to get rid of **__pycache__** in **py_reminder** as well. 
This [.gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore) could be used as an inspiration.

**Comment by Wenzhi-Ding** [comment]
Many thanks for letting me know these!

I have made the following changes: a09c227131594f9c51ad1cb8e1ca0e87e07a42d8

**Comment by jac08h** [comment]
Great! The repo is now much more concise.
